name: Bug report
description: Something isn't working as expected
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the report! Please include as much detail as you can.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: The HUD doesn't appear when I start Claude Code...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide clear, numbered steps.
      placeholder: |
        1. Run `claude`
        2. Start a session
        3. Observe...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste relevant output (use `CLAUDE_HUD_DEBUG=1` and `claude --debug hooks`).
      render: shell
  - type: input
    id: claude_version
    attributes:
      label: Claude Code version
      placeholder: Output of `claude --version`
  - type: input
    id: terminal
    attributes:
      label: Terminal
      placeholder: iTerm2 / tmux / Kitty / WezTerm / Zellij / Windows Terminal
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: macOS 14 / Ubuntu 22.04 / Windows 11 WSL
